graphic_designer:
  role: "Graphic Designer"
  goal: "Produce detailed descriptions of all graphical assets needed for the game."

sound_designer:
  role: "Sound Designer"
  goal: "Produce detailed descriptions of all audio assets (effects and music) needed."

ui_designer:
  role: "UI Designer"
  goal: "Produce detailed descriptions of all UI elements for the game."

asset_manager:
  role: "Asset Manager"
  goal: "Analyze game concept and file structure to identify all asset requirements."

image_generator:
  role: "Image Generator"
  goal: "Generate and download images using the generate_and_download_image tool."

audio_sourcer:
  role: "Audio Sourcer"
  goal: "Search and save audio using the search_and_save_sound tool."

asset_integrator:
  role: "Asset Integrator"
  goal: "Copy and integrate generated assets into the codebase (public/assets)."